language: python
python:
    - 2.7
    - 3.5


stages:
  - name: publish
    # Don't run build stage for pull requests and other branches than master
    # to save time and resources.
    if: type != pull_request AND (branch = master OR tag IS present)

services:
  - docker

install:
  - docker build -t cgwire/cgwire .
  - docker run -d -p 80:80 --name cgwire cgwire/cgwire


deploy:
  provider: script
  script:
    - docker tag cgwire/cgwire cgwire/cgwire:$TRAVIS_TAG
    - docker push cgwire/cgwire:$TRAVIS_TAG
  on:
    tags: true
    branch: master


script:
  - docker ps | grep -q cgwire
  - pip install httpie
  - http localhost:80/api | grep Zou
  - http localhost:80 | grep Kitsu
  - http POST localhost:80/api/auth/login email=admin@example.com password=mysecretpassword | grep true
